
@startuml
skinparam roundcorner 10
skinparam class {
	BackgroundColor #FFFFFF
	ArrowColor #000000
	BorderColor #000000
	BorderColor<<InnerType>> #777777
	BackgroundColor<<InnerType>> #EEEEEE
	BackgroundColor<<GidType>> #e4ffd4
	FontName Courier
	FontSize 12
}

skinparam note {
	BackgroundColor #dedede
	BorderColor #000000
	FontSize 10
}

skinparam classAttribute {
	FontName Courier
	FontSize 12
}

class JunctionLocationStreetsItem <<InnerType>> << ( ,#ff0000) >> {
}

class JunctionLocation <<InnerType>> << ( ,#ff00ff) >> {
}

class Junction <<GidType>> << ( ,#ff0000) >> {
}

note top of Junction
Junction is
a anchor point
of interest
of application
level
end note
class JunctionComment <<GidType>> << ( ,#007f00) >> {
}

note top of JunctionComment
Junction is
a anchor point
of interest
of application
level
end note
class JunctionContact <<GidType>> << ( ,#00007f) >> {
}

note top of JunctionContact
Junction is
a anchor point
of interest
of application
level
end note
class JunctionDocument <<GidType>> << ( ,#ff00ff) >> {
}

note top of JunctionDocument
Junction is
a anchor point
of interest
of application
level
end note
class JunctionJoined <<GidType>> << ( ,#0000ff) >> {
}

note top of JunctionJoined
Junction with
joined ObjectBase
end note
class JunctionNumber <<GidType>> << ( ,#007f00) >> {
}

note top of JunctionNumber
Junction is
a anchor point
of interest
of application
level
end note
class JunctionNumberType <<GidType>> << ( ,#7f007f) >> {
}

note top of JunctionNumberType
Technical identifier
for that junction
end note
class JunctionState <<GidType>> << ( ,#ff6100) >> {
}

note top of JunctionState
state of junction
end note
class JunctionType <<GidType>> << ( ,#00007f) >> {
}

note top of JunctionType
types of junctions
end note
class GeoArea  << ( ,#007f00) >> {
}

note top of GeoArea
Area geo-type
end note
class GeoPoint  << ( ,#ff6100) >> {
}

note top of GeoPoint
Single point
geo-type
end note
class ObjectBase <<GidType>> << ( ,#007f00) >> {
}

note top of ObjectBase
Object is a
anchor point
of interest
of application
level, that's
the minimal
information
about that
end note
class GeoMultiline  << ( ,#ff0000) >> {
}

note top of GeoMultiline
Multiline geo-type
end note
class ListEntry  << ( ,#0000ff) >> {
}

note top of ListEntry
type for entries
that have references
to look-up
tables - as
an more dynamic
alternative
to enums
end note
class Region <<GidType>> << ( ,#00007f) >> {
}

note top of Region
A region is
some kind of
a logical group
that could
be set for
some entries.
It allows 'vertical'
restrictions
of object visibility
end note
class Tenant <<GidType>> << ( ,#7f007f) >> {
}

note top of Tenant
Tenant of a
running application.
end note
class Tag <<GidType>> << ( ,#5f005f) >> {
}

note top of Tag
A tag is some
kind of a global
keyword that
could be set
for some entries
end note
class ObjectBaseGis <<InnerType>> << ( ,#9b0000) >> {
}

class ObjectGroup <<GidType>> << ( ,#9b0000) >> {
}

note top of ObjectGroup
Groups of objects
(f.e. intersections,
INES nets,
public transport
route, ...)
end note
class Comment  << ( ,#0000ff) >> {
}

note top of Comment
A comment for
an data entry
end note
class Contact  << ( ,#ff6100) >> {
}

note top of Contact
contact to
a specific
entity
end note
class Address  << ( ,#007f00) >> {
}

class ContactData  << ( ,#9b0000) >> {
}

note top of ContactData
contact data
for a person
or address
end note
class Person  << ( ,#ff00ff) >> {
}

note top of Person
simple person
definition
end note
class AddressPerson  << ( ,#5f005f) >> {
}

note top of AddressPerson
a person that
is linked to
an address
end note
class AddressType <<GidType>> << ( ,#ff0000) >> {
}

note top of AddressType
type of a document
end note
class ContactType <<GidType>> << ( ,#ff6100) >> {
}

note top of ContactType
type of a contact
end note
class Document  << ( ,#9b0000) >> {
}

note top of Document
description
of a contained
document
end note
class DocumentType <<GidType>> << ( ,#ff0000) >> {
}

note top of DocumentType
type of a document
end note
class Incident <<GidType>> << ( ,#0000ff) >> {
}

note top of Incident
A detected
failure state
that needs
some actions
to solve it
end note
class IncidentComment <<GidType>> << ( ,#ff6100) >> {
}

note top of IncidentComment
Comment entries
to incidents
end note
class IncidentDocument <<GidType>> << ( ,#ff0000) >> {
}

note top of IncidentDocument
documents linked
to incident
entries
end note
class IncidentJoined <<GidType>> << ( ,#ff00ff) >> {
}

note top of IncidentJoined
Incident with
joined ObjectBase
end note
class IncidentNumber  << ( ,#0000ff) >> {
}

class IncidentRawData  << ( ,#007f00) >> {
}

class IncidentState  << ( ,#7f007f) >> {
}

class IncidentStateType <<GidType>> << ( ,#ff6100) >> {
}

note top of IncidentStateType
occurs, entered,
resolved, ...
end note
class IncidentTag <<GidType>> << ( ,#00007f) >> {
}

note top of IncidentTag
key-word for
additional
incident tagging
end note
class IncidentType <<GidType>> << ( ,#007f00) >> {
}

note top of IncidentType
types of incidents
end note
class OpMessage <<GidType>> << ( ,#ff6100) >> {
}

note top of OpMessage
General system
operation message
end note
class OpMessageJoined <<GidType>> << ( ,#00007f) >> {
}

note top of OpMessageJoined
OpMessage with
joined ObjectBase
end note
class OpMessageRawData  << ( ,#007f00) >> {
}

note top of OpMessageRawData
container for
additional,
app-specific
content
end note
class OpMessageSender <<GidType>> << ( ,#9b0000) >> {
}

note top of OpMessageSender
Who sends the
message
end note
class OpMessageTag <<GidType>> << ( ,#5f005f) >> {
}

note top of OpMessageTag
Tag to group
messages
end note
class OpMessageType <<GidType>> << ( ,#ff0000) >> {
}

note top of OpMessageType
types of message
end note
hide methods
hide attributes
            Junction ..  ObjectBase #007f00
            Junction ..  JunctionState #ff6100
            Junction ..  Tenant #7f007f
            Junction ..  JunctionType #00007f
            JunctionComment ..  Junction #ff0000
            JunctionComment ..  Tenant #7f007f
            JunctionContact ..  ContactType #ff6100
            JunctionContact ..  Junction #ff0000
            JunctionContact ..  Tenant #7f007f
            JunctionDocument ..  DocumentType #ff0000
            JunctionDocument ..  Junction #ff0000
            JunctionDocument ..  Tenant #7f007f
            JunctionJoined ..  ObjectBase #007f00
            JunctionJoined ..  JunctionState #ff6100
            JunctionJoined ..  Tenant #7f007f
            JunctionJoined ..  JunctionType #00007f
            JunctionNumber ..  Junction #ff0000
            JunctionNumber ..  Tenant #7f007f
            JunctionNumber ..  JunctionNumberType #7f007f
            JunctionNumberType ..  Tenant #7f007f
            JunctionState ..  Tenant #7f007f
            JunctionType ..  Tenant #7f007f
            ObjectBase ..  ObjectGroup #9b0000
            ObjectBase .. "many" Region #00007f
            ObjectBase .. "many" Tag #5f005f
            ObjectBase ..  Tenant #7f007f
            Region ..  Tenant #7f007f
            Tag ..  Tenant #7f007f
            ObjectGroup ..  Tenant #7f007f
            Contact ..  ContactType #ff6100
            Address ..  AddressType #ff0000
            AddressType ..  Tenant #7f007f
            ContactType ..  Tenant #7f007f
            Document ..  DocumentType #ff0000
            DocumentType ..  Tenant #7f007f
            Incident ..  ObjectBase #0000ff
            Incident .. "many" OpMessage #ff00ff
            Incident .. "many" Incident #0000ff
            Incident .. "many" IncidentTag #00007f
            Incident ..  Tenant #5f005f
            Incident ..  IncidentType #007f00
            IncidentComment ..  Incident #0000ff
            IncidentComment ..  Tenant #5f005f
            IncidentDocument ..  DocumentType #5f005f
            IncidentDocument ..  Incident #0000ff
            IncidentDocument ..  Tenant #5f005f
            IncidentJoined ..  ObjectBase #0000ff
            IncidentJoined .. "many" OpMessage #ff00ff
            IncidentJoined .. "many" Incident #0000ff
            IncidentJoined .. "many" IncidentTag #00007f
            IncidentJoined ..  Tenant #5f005f
            IncidentJoined ..  IncidentType #007f00
            IncidentState ..  IncidentStateType #ff6100
            IncidentStateType .. "many" IncidentType #007f00
            IncidentStateType ..  Tenant #5f005f
            IncidentTag ..  Tenant #5f005f
            IncidentType .. "many" ObjectGroup #007f00
            IncidentType ..  Tenant #5f005f
            OpMessage ..  ObjectBase #0000ff
            OpMessage .. "many" OpMessage #ff6100
            OpMessage ..  OpMessageSender #9b0000
            OpMessage .. "many" OpMessageTag #5f005f
            OpMessage ..  Tenant #5f005f
            OpMessage ..  OpMessageType #ff0000
            OpMessageJoined ..  ObjectBase #0000ff
            OpMessageJoined .. "many" OpMessage #ff6100
            OpMessageJoined ..  OpMessageSender #9b0000
            OpMessageJoined .. "many" OpMessageTag #5f005f
            OpMessageJoined ..  Tenant #5f005f
            OpMessageJoined ..  OpMessageType #ff0000
            OpMessageSender ..  Tenant #5f005f
            OpMessageTag ..  Tenant #5f005f
            OpMessageType ..  Tenant #5f005f
footer powered by plantuml, created with jsonCodeGen
@enduml
