@startuml
title: Communication between components\nrelated to authentication/authorization
rectangle "Browser session" {
node "front-end-1" as f1
node "front-end-2" as f2
node "front-end-3" as f3
}

rectangle "Backend" {
    node "service 1" as s1
    node "service 2" as s2

    node "service 3" as s3
    node "service 4" as s4
}
node Keycloak

f1 --> Keycloak: request token\nfirst login

f1 -> s1: Token
f2 -> s2: Token
f3 -> s2: Token

s2 <--> s4: authenticated w/\nbearer token
s2 <--> s3: authenticated w/\nforwarded user token

Keycloak <- s1: validate Token
Keycloak <- s2: validate Token

note bottom of s4
this comm don't
share user data
between services
end note

note bottom of s3
this comm don't
share user data
between services
end note

note left of Keycloak
The token contains
information about
user and granted
roles in system
end note

@enduml